In [ ]:
import numpy as np
matrix_1 = np.array([[2,3],[5,6]]
              )
print(matrix_1)

[[2 3]
 [5 6]]


In [ ]:
matrix_1.shape

(2, 2)

In [32]:
matrix_2= np.array([[1,3],[4,6]])
print(matrix_2)

[[1 3]
 [4 6]]


In [33]:
matrix_2.shape

(2, 2)

Creating matrices with random values


In [34]:

random_matrix_1 = np.random.rand(3, 3)
print( random_matrix_1)

random_matrix_2 = np.random.randint(1, 10, size=(2, 4))
print( random_matrix_2)

random_int = np.random.randint(5, size=(3,3)
)
print( random_int)


[[0.73681297 0.76340873 0.86791569]
 [0.2202557  0.59788463 0.94165586]
 [0.65713534 0.6165659  0.74065461]]
[[4 5 5 2]
 [9 4 6 8]]
[[3 4 1]
 [2 3 4]
 [2 0 4]]


Matrix with all the values as 1

In [35]:
matrix_3 = np.ones((3, 3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [36]:
matrix_4 = np.eye(10, dtype=int)
print(matrix_4)

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


In [37]:
matrix_5 = np.eye(3, dtype=int)
print(matrix_5)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [38]:
# matrix with random integer transpose
a = np.random.randint(100, size=(4,5))

In [39]:
print(a)

[[ 3 51 86 31 88]
 [84 36 79 25 44]
 [24 29 27 53 99]
 [80 69 90 50 96]]


In [40]:
transpose_of_a = np.transpose(a)

In [41]:
print(transpose_of_a)

[[ 3 84 24 80]
 [51 36 29 69]
 [86 79 27 90]
 [31 25 53 50]
 [88 44 99 96]]


In [42]:
# multiplying matrixes the number of columns in the first matrix is equal to the number of rows in the second matri


In [46]:
sum = matrix_1 + matrix_2

print(sum)

[[ 3  6]
 [ 9 12]]


In [47]:
diff = matrix_1 - matrix_2

In [48]:
print(diff)

[[1 0]
 [1 0]]


In [57]:
multiply = np.multiply(4,matrix_2)

In [58]:
print(multiply)

[[ 4 12]
 [16 24]]
